routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes(['verify' => true]);
Broadcast::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/settings', 'SettingsController@index');
Route::post('/settings/profile', 'SettingsController@updateProfile');
Route::post('/settings/password', 'SettingsController@updatePassword');
Route::post('/settings/location', 'SettingsController@updateLocation');

Route::get('/user/{user}');

Route::group(['prefix' => '/ticket', 'middleware' => ['auth', 'verified'], 'namespace' => 'HelpDesk\Tickets'], function () {
    Route::get('/create', 'TicketController@create');
    Route::post('/create', 'TicketController@insert');
    Route::get('/{ticket}', 'TicketController@index');
    Route::get('/{ticket}/edit', 'TicketController@edit');
    Route::post('/{ticket}/edit', 'TicketController@update');
    Route::group(['prefix' => '/{ticket}/comment'], function () {
        Route::post('/create', 'CommentController@insert');
        Route::get('/{comment}/edit', 'CommentController@edit');
        Route::post('/{comment}/edit', 'CommentController@update');
        Route::delete('/{comment}/delete', 'CommentController@delete');
    });
});

/*
 * These routes are only accessible to IT staff
 */
Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'staff', 'verified']], function () {
    Route::get('/');
    // Manage locations
    Route::group(['prefix' => '/locations'], function () {
        Route::get('/', 'Locations\DistrictController@index');
        Route::get('/create', 'Locations\DistrictController@create');
        Route::post('/create', 'Locations\DistrictController@insert');
        Route::get('/{district}', 'Locations\DistrictController@single');
        Route::get('/{district}/edit', 'Locations\DistrictController@edit');
        Route::post('/{district}/edit', 'Locations\DistrictController@update');
        Route::get('/{district}/create', 'Locations\BuildingController@create');
        Route::post('/{district}/create', 'Locations\BuildingController@insert');
        Route::get('/{district}/{building}', 'Locations\BuildingController@index');
        Route::get('/{district}/{building}/edit', 'Locations\BuildingController@edit');
        Route::post('/{district}/{building}/edit', 'Locations\BuildingController@update');
    });
    // Manage Users
    Route::group(['prefix' => '/users', 'middleware' => ['auth', 'staff', 'verified']], function () {
        Route::get('/');
        Route::get('/create');
        Route::post('/create');
        Route::get('/{user}');
        Route::get('/{user}/edit');
        Route::post('/{user}/edit');
    });

    Route::group(['prefix' => '/help-desk', 'middleware' => ['auth', 'staff', 'verified'], 'namespace' => 'HelpDesk\Meta'], function () {
        Route::group(['prefix' => '/status'], function () {
            Route::get('/', 'StatusController@index');
            Route::get('/create', 'StatusController@create');
            Route::post('/create', 'StatusController@insert');
            Route::get('/edit/{status}', 'StatusController@edit');
            Route::post('/edit/{status}', 'StatusController@update');
        });

        Route::group(['prefix' => '/category'], function () {
            Route::get('/', 'CategoryController@index');
            Route::get('/create', 'CategoryController@create');
            Route::post('/create', 'CategoryController@insert');
            Route::get('/edit/{category}', 'CategoryController@edit');
            Route::post('/edit/{category}', 'CategoryController@update');
        });

        Route::group(['prefix' => '/priority'], function () {
            Route::get('/', 'PriorityController@index');
            Route::get('/create', 'PriorityController@create');
            Route::post('/create', 'PriorityController@insert');
            Route::get('/edit/{priority}', 'PriorityController@edit');
            Route::post('/edit/{priority}', 'PriorityController@update');
        });
    });
});

app/Models/Comment.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Markdown;

/**
 * App\Comment
 *
 * @property int $id
 * @property string $comment
 * @property int $ticket_id
 * @property int $user_id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Ticket $ticket
 * @property-read User $user
 * @method static Builder|Comment whereComment($value)
 * @method static Builder|Comment whereCreatedAt($value)
 * @method static Builder|Comment whereId($value)
 * @method static Builder|Comment whereTicketId($value)
 * @method static Builder|Comment whereUpdatedAt($value)
 * @method static Builder|Comment whereUserId($value)
 * @mixin Eloquent
 * @method static Builder|Comment newModelQuery()
 * @method static Builder|Comment newQuery()
 * @method static Builder|Comment query()
 */
class Comment extends Model
{

    protected $fillable = ['comment', 'ticket_id', 'user_id'];

    /**
     * Return HTML for comment
     *
     * @return string
     */
    public function getHtmlCommentAttribute()
    {
        return Markdown::convertToHtml("{$this->comment}");
    }

    /**
     * @return BelongsTo
     */
    public function ticket()
    {
        return $this->belongsTo('App\Models\Ticket');
    }

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }
}

app/Models/Ticket.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Eloquent;
use Hashids;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Markdown;
use OwenIt\Auditing\Auditable as AuditableTrait;
use OwenIt\Auditing\Contracts\Auditable;
use OwenIt\Auditing\Models\Audit;

/**
 * App\Ticket
 *
 * @property int $id
 * @property string $hash
 * @property string $description
 * @property int $district_id
 * @property int $building_id
 * @property string $room
 * @property int $user_id
 * @property int $priority_id
 * @property int $category_id
 * @property string $completed_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Collection|User[] $assignees
 * @property-read Collection|Audit[] $audits
 * @property-read Building $building
 * @property-read Collection|Comment[] $comments
 * @property-read District $district
 * @property-read User $user
 * @method static Builder|Ticket whereBuildingId($value)
 * @method static Builder|Ticket whereCategoryId($value)
 * @method static Builder|Ticket whereCompletedAt($value)
 * @method static Builder|Ticket whereCreatedAt($value)
 * @method static Builder|Ticket whereDescription($value)
 * @method static Builder|Ticket whereDistrictId($value)
 * @method static Builder|Ticket whereHash($value)
 * @method static Builder|Ticket whereId($value)
 * @method static Builder|Ticket wherePriorityId($value)
 * @method static Builder|Ticket whereRoom($value)
 * @method static Builder|Ticket whereUpdatedAt($value)
 * @method static Builder|Ticket whereUserId($value)
 * @mixin Eloquent
 * @property int $status_id
 * @property-read mixed $html_description
 * @method static Builder|Ticket newModelQuery()
 * @method static Builder|Ticket newQuery()
 * @method static Builder|Ticket query()
 * @method static Builder|Ticket whereStatusId($value)
 */
class Ticket extends Model implements Auditable
{
    use AuditableTrait;

    protected $fillable = ['description', 'priority_id', 'category_id', 'user_id', 'room', 'district_id', 'building_id'];

    /**
     * @return BelongsTo
     */
    public function district()
    {
        return $this->belongsTo('App\Models\District');
    }

    /**
     * @return BelongsTo
     */
    public function building()
    {
        return $this->belongsTo('App\Models\Building');
    }

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * @return HasMany
     */
    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }

    /**
     * @return BelongsToMany
     */
    public function assignees()
    {
        return $this->belongsToMany('App\Models\User')->withTimestamps();
    }

    /**
     * @return BelongsTo
     */
    public function status()
    {
        return $this->belongsTo('App\Models\Status');
    }

    /**
     * @return BelongsTo
     */
    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    /**
     * @return BelongsTo
     */
    public function priority()
    {
        return $this->belongsTo('App\Models\Priority');
    }

    /**
     * @return string
     */
    public function getHtmlDescriptionAttribute()
    {
        return Markdown::convertToHtml("{$this->description}");
    }

    /**
     * The boot method
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $hash = null;
            while (Ticket::whereHash($hash)->get()->count() > 0 || $hash === null) {
                // Based on my calculations this code should provide 1,406,408,600,000 possible combinations, I might be wrong though
                $hash = Hashids::encode(gmp_random_bits(31));
            }
            $status = Status::whereDefault(true)->first(['id']);
            $model->status_id = $status->id;
            $model->hash = $hash;
            $model->completed_at = null;
        });
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'hash';
    }

}

app/Http/Controllers/HelpDesk/Tickets/CommentController.php
<?php

namespace App\Http\Controllers\HelpDesk\Tickets;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Ticket;
use Auth;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function insert(Request $request, Ticket $ticket)
    {
        $this->validate($request, [
            'comment' => 'required|string'
        ]);
        $comment = Comment::create([
            'comment' => $request->input('comment'),
            'user_id' => Auth::user()->id,
            'ticket_id' => $ticket->id
        ]);
        if ($request->ajax()) {
            return response()->json($comment);
        } else {
            return redirect()->back();
        }
    }

    public function edit(Request $request, Ticket $ticket, Comment $comment)
    {
        return view();
    }

    public function update(Request $request, Ticket $ticket, Comment $comment)
    {
        tap($comment)->update($request->only(['comment']));
        if ($request->ajax()) {
            return response()->json($comment);
        } else {
            return redirect()->back();
        }
    }
}

app/Http/Controllers/HelpDesk/Tickets/TicketController.php
<?php

namespace App\Http\Controllers\HelpDesk\Tickets;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Priority;
use App\Models\Ticket;
use App\Models\User;
use Auth;
use Cache;
use Illuminate\Http\Request;

class TicketController extends Controller
{
    public function index(Request $request, Ticket $ticket)
    {
        return view('ticket.view', ['ticket' => $ticket]);
    }

    public function create(Request $request)
    {
        $categories = Cache::tags('category')->remember('category.all', now()->addHour(1), function () {
            return Category::all();
        });
        $priorities = Cache::tags('priority')->remember('priority.all', now()->addHour(1), function () {
            return Priority::all();
        });
        return view('ticket.create', ['categories' => $categories, 'priorities' => $priorities]);
    }

    public function insert(Request $request)
    {
        $this->validate($request, [
            'description' => 'required|string',
            'priority_id' => 'required|exists:priorities,id',
            'category_id' => 'required|exists:categories,id',
            'user_id' => 'nullable|exists:users,id',
        ]);
        // If a user is specified in the form use that otherwise default to the user that created the ticket
        $user = User::whereId($request->input('user_id'))->first() ?? Auth::user();
        $ticket = Ticket::create([
            'description' => $request->input('description'),
            'priority_id' => $request->input('priority_id'),
            'category_id' => $request->input('category_id'),
            'user_id' => $user->id,
            'room' => $user->room,
            'district_id' => $user->district->id,
            'building_id' => $user->building->id
        ]);
        Cache::tags('tickets')->clear();
        return redirect("/ticket/$ticket->hash");
    }

    public function edit(Request $request, Ticket $ticket)
    {
        return view('ticket.edit', ['ticket' => $ticket]);
    }

    public function update(Request $request, Ticket $ticket)
    {
        $this->validate($request, [
            'description' => 'required|string',
            'priority_id' => 'required|exist:priorities,id',
            'category_id' => 'required|exist:categories,id',
        ]);
        tap($ticket)->update($request->only(['description', 'priority', 'category']));
        return redirect("/ticket/$ticket->hash");
    }
}

resources/views/ticket/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">{{ __('Create Ticket') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{ url('/ticket/create') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="description">{{ __('Description') }}</label>
                                <div class="col-md-12">
                                    <markdown-input class="{{ $errors->has('description') ? ' is-invalid' : '' }}"
                                                    box-id="description" box-name="description"
                                                    value="{{ old('description') }}"></markdown-input>
                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col">
                                    <label for="priority_id">{{ __('Priority') }}</label>
                                    <select id="priority_id" name="priority_id"
                                            class="custom-select{{ $errors->has('priority_id') ? ' is-invalid' : '' }}">
                                        <option>Select a priority</option>
                                        @foreach($priorities as $priority)
                                            <option value="{{ $priority->id }}">{{ $priority->name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('priority_id'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('priority_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="col">
                                    <label for="category_id">{{ __('Category') }}</label>
                                    <select id="category_id" name="category_id"
                                            class="custom-select{{ $errors->has('category_id') ? ' is-invalid' : '' }}">
                                        <option>Select a category</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category_id'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row justify-content-center">
                                <button type="submit" class="btn btn-raised btn-primary">Create Ticket</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ticket/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Ticket') }} - {{ $ticket->hash }}</div>
                    <div class="card-body">
                        {!! $ticket->html_description !!}
                    </div>
                </div>
                @foreach($ticket->comments as $comment)
                    <div class="card mt-2">
                        <div class="card-body">
                            {!! $comment->html_comment !!}
                        </div>
                        <div class="card-footer">
                            <div class="text-muted">
                                <timeago datetime="{{ $comment->created_at }}" :auto-update="60"></timeago>
                                from {{ $comment->user->name }}
                                <div class="flex"></div>
                            </div>
                        </div>
                    </div>
                @endforeach
                <div class="card mt-2">
                    <div class="card-body">
                        <form method="POST" action="{{ url("/ticket/$ticket->hash/comment/create") }}">
                            @csrf
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <markdown-input class="{{ $errors->has('comment') ? ' is-invalid' : '' }}"
                                                    box-id="comment" box-name="comment"
                                                    value="{{ old('comment') }}"></markdown-input>
                                    @if ($errors->has('comment'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('comment') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row justify-content-center">
                                <button type="submit" class="btn btn-raised btn-primary">Post Comment</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mt-4 mt-md-0">
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#details" role="tab"
                                   aria-controls="details" aria-selected="true">Details</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#computer" role="tab"
                                   aria-controls="computer" aria-selected="false">Computer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                                   aria-controls="contact" aria-selected="false">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="details" role="tabpanel"
                                 aria-labelledby="details-tab">
                                <dl class="row">
                                    <dt class="col-sm-4">District</dt>
                                    <dd class="col-sm-8">{{ $ticket->district->name }}</dd>

                                    <dt class="col-sm-4">Building</dt>
                                    <dd class="col-sm-8">{{ $ticket->building->name }}</dd>

                                    <dt class="col-sm-4">Room</dt>
                                    <dd class="col-sm-8">{{ $ticket->user->room }}</dd>
                                </dl>
                                <div class="dropdown-divider"></div>
                                <dl class="row">
                                    <dt class="col-sm-4">Status</dt>
                                    <dd class="col-sm-8">{{ $ticket->status->name }}</dd>

                                    <dt class="col-sm-4">Priority</dt>
                                    <dd class="col-sm-8">{{ $ticket->priority->name }}</dd>

                                    <dt class="col-sm-4">Category</dt>
                                    <dd class="col-sm-8">{{ $ticket->category->name }}</dd>
                                </dl>
                                <div class="dropdown-divider"></div>
                                <dl class="row">
                                    <dt class="col-sm-4">Created</dt>
                                    <dd class="col-sm-8">
                                        <timeago datetime="{{ $ticket->created_at }}" :auto-update="60"></timeago>
                                    </dd>

                                    <dt class="col-sm-4">Updated</dt>
                                    <dd class="col-sm-8">
                                        <timeago datetime="{{ $ticket->updated_at }}" :auto-update="60"></timeago>
                                    </dd>
                                </dl>
                            </div>
                            <div class="tab-pane fade" id="computer" role="tabpanel" aria-labelledby="computer-tab">
                                <div class="alert alert-info" role="alert">
                                    Feature Coming Soon!
                                </div>
                            </div>
                            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                                <dl class="row">
                                    <dt class="col-sm-4">Name</dt>
                                    <dd class="col-sm-8">{{ $ticket->user->name }}</dd>

                                    <dt class="col-sm-4">E-Mail</dt>
                                    <dd class="col-sm-8"><a
                                                href="mailto:{{ $ticket->user->email }}">{{ $ticket->user->email }}</a>
                                    </dd>

                                    @if($ticket->user->phone_number)
                                        <dt class="col-sm-4">Phone</dt>
                                        <dd class="col-sm-8">{{ $ticket->user->phone_number }}</dd>
                                    @endif

                                    @if($ticket->user->phone_extension)
                                        <dt class="col-sm-4">Extension</dt>
                                        <dd class="col-sm-8">{{ $ticket->user->phone_extension }}</dd>
                                    @endif
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection